// react_client/src/app/subjects/Edit/page.tsx
"use client"
import { IModule } from "@/domain/IModule";
import { ISubject } from "@/domain/ISubject";
import CurriculumService from "@/services/CurriculumService";
import ModuleService from "@/services/ModuleService";
import SubjectService from "@/services/SubjectService";
import { useEffect, useState } from "react";

export default function Edit() {
    const [modules, setModules] = useState<IModule[]>();
    const [subject, setSubject] = useState<ISubject>();
    const [isLoading, setIsLoading] = useState(true);
    const subjectId = "typeof window !== 'undefined' ? localStorage.getItem(subjectId) : null"
    const userInfo = "typeof window !== 'undefined' ? localStorage.getItem('userInfo') : null"
    //const { userInfo, setUserInfo } = useContext(AppContext)!;

    const [validationError, setvalidationError] = useState("");

    const [label, setLabel] = useState("");
    const [description, setDescription] = useState("");
    const [eap, setEap] = useState(0);
    const [moduleId, setModuleId] = useState("");


    const ValidateAndSave = async () => {

        if (label == ""){
            setvalidationError("Label field is required!");
            return;
        }
        if (userInfo != undefined){
            const response = await SubjectService.put(userInfo, subjectId!, label, description, eap, moduleId)
            if (response.errors && response.errors.length > 0) {
                setvalidationError(response.errors[0]);
            } else {
                window.location.replace("/subjects");
            }
        } else{
            window.location.replace("/Identity/login");
        }
    };

    const loadData = async () => {
        const response = await SubjectService.get(subjectId!, userInfo!)
        if (response.data) {
            setSubject(response.data);
            setLabel(response.data.label)
            setDescription(response.data.description)
            setEap(response.data.eap)
            setModuleId(response.data.moduleId)
        } else {
            if (response.errors && response.errors.length > 0) {
                return (
                    <>
                        Server error: {response.errors[0]}
                    </>
                )
            }
        }
        const curricula = await CurriculumService.getAll();
        if (curricula.data){
            const response = await ModuleService.getAll(curricula.data[0].id)
            if (response.data) {
                setModules(response.data);
            }
        }
        setIsLoading(false);
    };
    useEffect(() => { loadData() }, []);

    if (isLoading){
        return (<h1>Details - LOADING</h1>);
        
    }
    return (
        <>
        <div className="row">
            <div className="col-md-5">
                <h2>Edit Subject</h2>
                <hr />
                <div className="text-danger" role="alert">{validationError}</div>
                <div className="form-floating mb-3">
                    <input
                        value={label}
                        onChange={(e) => { setLabel(e.target.value); setvalidationError(""); }}
                        id="label" type="text" className="form-control" autoComplete="label" placeholder="Label" />
                    <label htmlFor="label" className="form-label">Label</label>
                </div>
                <div className="form-floating mb-3">
                    <input
                        value={description}
                        onChange={(e) => { setDescription(e.target.value); setvalidationError(""); }}
                        id="description" type="text" className="form-control" autoComplete="description" placeholder="Võsa Pets" />
                    <label htmlFor="description" className="form-label">Description</label>
                </div>
                <div className="form-floating mb-3">
                    <input
                        value={eap}
                        onChange={(e) => { setEap(Number.parseInt(e.target.value)); setvalidationError(""); }}
                        id="eap" type="number" className="form-control" autoComplete="eap" placeholder="0" />
                    <label htmlFor="eap" className="form-label">EAP</label>
                </div>

                <div className="form-group">
                    <label className="form-label" htmlFor="moduleId">Module</label>
                    <select
                    value={moduleId}
                    onChange={(e) => { setModuleId(e.target.value) }}
                    className="form-control" id="moduleId">
                        <option></option>
                        {modules!.map((module) => 
                            <option value={module.id} key={module.id}>{module.label}</option>
                        )}
                    </select>
                </div>
                <div>
                    <button onClick={(e) => ValidateAndSave()} className="w-100 btn btn-lg btn-primary">Save</button>
                </div>
            </div>
            <div>
                <a href="./">Back to List</a>
            </div>
        </div>
        </>
    );
  }

// vue_client/src/views/calendar/Edit.vue
<script setup lang="ts">
import type { ISubject } from '@/domain/ISubject'
import EventService from '@/services/EventService'
import SubjectService from '@/services/SubjectService'
import { ref, watch } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()

const props = defineProps({
  id: String
})

const userInfo = localStorage.getItem('userInfo')
let validationErrors = ref('')
let label = ref('')
let description = ref('')
let from = ref('')
let until = ref('')
let subjectId = ref('')
let subjects = ref<ISubject[]>()
const loading = ref(true)
const loadData = async () => {
  subjects.value = (await SubjectService.getAll(userInfo!)).data
  const event = (await EventService.get(props.id!, userInfo!)).data
  label.value = event?.label!
  description.value = event?.description!
  from.value = new Date(event?.from!).toISOString().substring(0, 16)
  until.value = new Date(event?.until!).toISOString().substring(0, 16)
  subjectId.value = event?.subjectId!
}

const validateAndSave = async () => {
  if (label.value == '' || from.value == '' || until.value == '' || subjectId.value == '') {
    validationErrors.value = "Only 'Description' field is not required"
    return
  }

  const res = await EventService.update(
    userInfo!,
    props.id!,
    label.value,
    description.value,
    from.value,
    until.value,
    subjectId.value
  )
  if (!res.errors) {
    router.push({ name: 'Calendar' })
  }
}

loadData()
watch(subjects, async (newValue, oldValue) => {
  console.log(subjects)
  loading.value = false
})
</script>

<template>
  <h1>Edit</h1>

  <h4>Event</h4>
  <hr />
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <label class="control-label" for="Ewent_Label">Label</label>
        <input v-model="label" class="form-control" type="text" />
      </div>
      <div class="form-group">
        <label class="control-label" for="Ewent_Description">Description</label>
        <input v-model="description" class="form-control" type="text" />
      </div>
      <div class="form-group">
        <label class="control-label" for="Ewent_From">From</label>
        <input v-model="from" class="form-control" type="datetime-local" />
      </div>
      <div class="form-group">
        <label class="control-label" for="Ewent_Until">Until</label>
        <input v-model="until" class="form-control" type="datetime-local" />
      </div>
      <div class="form-group">
        <label class="control-label" for="Ewent_SubjectId">SubjectId</label>
        <select v-model="subjectId" class="form-control">
          <option v-for="subject in subjects" :key="subject.id" :value="subject.id">
            {{ subject.label }}
          </option>
        </select>
      </div>
      <div class="form-group">
        <button @click="validateAndSave()" type="submit" value="Edit" class="btn btn-primary">
          Save
        </button>
      </div>
    </div>
  </div>

  <div>
    <RouterLink class="link" :to="{ name: 'Calendar' }">Back to List</RouterLink>
  </div>
</template>
