// react_client/src/app/Identity/login/page.tsx
"use client"

import AccountService from "@/services/AccountService";
import { AppContext } from "@/state/AppContext";
import { useRouter } from "next/navigation";
import { useContext, useState } from "react";

export default function Login() {
    const router = useRouter();
    const [email, setEmail] = useState("admin@eesti.ee");
    const [pwd, setPwd] = useState("Kala.maja1");

    const [validationError, setvalidationError] = useState("");

    const { userInfo, setUserInfo } = useContext(AppContext)!;

    const validateAndLogin = async () => {
        if (email.length < 5 || pwd.length < 6) {
            setvalidationError("Invalid input lengths");
            return;
        }

        const response = await AccountService.login(email, pwd);
        if (response.data) {
            "typeof window !== 'undefined' ? localStorage.setItem('userInfo', JSON.stringify(response.data, null, 4)) : null;"
            setUserInfo(response.data);
            //router.push("/");
            window.location.replace("/");
        }

        if (response.errors && response.errors.length > 0) {
            setvalidationError(response.errors[0]);
        }
    }

    return (
        <div className="row">
            <div className="col-md-5">
                <h2>Log in</h2>
                <hr />
                <div className="text-danger" role="alert">{validationError}</div>
                <div className="form-floating mb-3">
                    <input
                        value={email}
                        onChange={(e) => { setEmail(e.target.value); setvalidationError(""); }}
                        id="email" type="email" className="form-control" autoComplete="email" placeholder="name@example.com" />
                    <label htmlFor="email" className="form-label">Email</label>
                </div>
                <div className="form-floating mb-3">
                    <input
                        value={pwd}
                        onChange={(e) => { setPwd(e.target.value); setvalidationError(""); }}
                        id="password" type="password" className="form-control" autoComplete="password" placeholder="password" />
                    <label htmlFor="password" className="form-label">Password</label>
                </div>
                <div>
                    <button onClick={(e) => validateAndLogin()} className="w-100 btn btn-lg btn-primary">Log in</button>
                </div>
            </div>
        </div>

    );
}

// vue_client/src/views/identity/Login.vue
<script setup lang="ts">
import router from '@/router'
import AccountService from '@/services/AccountService'
import { useAuthStore } from '@/stores/auth'
import { ref } from 'vue'

const authStore = useAuthStore()

let loginName = ref('')
let loginPassword = ref('')

let loginIsOngoing = ref(false)
let errors = ref<string[]>([])

const doLogin = async () => {
  loginIsOngoing.value = true

  const res = await AccountService.login(loginName.value, loginPassword.value)

  if (res.data) {
    authStore.jwt = res.data.jwt
    authStore.refreshToken = res.data.refreshToken
    authStore.userName = res.data.firstname + ' ' + res.data.lastname
    localStorage.setItem('userInfo', JSON.stringify(res.data, null, 0))
    errors.value = []
    window.location.replace('/')
  } else {
    errors.value = res.errors!
  }

  loginIsOngoing.value = false
}
</script>

<template>
  <h1>Log in</h1>
  <div class="row">
    <div class="col-md-6">
      <section>
        <form id="account" method="post">
          <hr />

          <div>{{ errors.join(',') }}</div>
          <div class="form-floating mb-3">
            <input
              v-model="loginName"
              class="form-control"
              autocomplete="username"
              aria-required="true"
              placeholder="name@example.com"
              type="email"
              id="Input_Email"
              name="Input.Email"
            />
            <label class="form-label" for="Input_Email">Email</label>
          </div>

          <div class="form-floating mb-3">
            <input
              v-model="loginPassword"
              class="form-control"
              autocomplete="current-password"
              aria-required="true"
              placeholder="password"
              type="password"
              id="Input_Password"
              name="Input.Password"
            />
            <label class="form-label" for="Input_Password">Password</label>
          </div>

          <div>
            <button
              @click.prevent="doLogin"
              id="login-submit"
              type="submit"
              class="w-100 btn btn-lg btn-primary"
            >
              {{ loginIsOngoing ? 'Wait...' : 'Login' }}
            </button>
          </div>
        </form>
      </section>
    </div>
  </div>
</template>

<style scoped></style>
