// vue_client/src/views/calendar/Create.vue
<script setup lang="ts">
import type { ISubject } from '@/domain/ISubject'
import EventService from '@/services/EventService'
import SubjectService from '@/services/SubjectService'
import { ref, watch } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()

const userInfo = localStorage.getItem('userInfo')
const validationErrors = ref('')
const label = ref('')
const description = ref('')
const from = ref('')
const until = ref('')
const subjectId = ref('')
const subjects = ref<ISubject[]>()
const loading = ref(true)
const loadData = async () => {
  subjects.value = (await SubjectService.getAll(userInfo!)).data
}

const validateAndCreate = async () => {
  if (label.value == '' || from.value == '' || until.value == '' || subjectId.value == '') {
    validationErrors.value = "Only 'Description' field is not required"
    return
  }

  const res = await EventService.post(
    userInfo!,
    label.value,
    description.value,
    from.value,
    until.value,
    subjectId.value
  )
  if (res.data) {
    router.push({ name: 'Calendar' })
  }
}

loadData()
watch(subjects, async (newValue, oldValue) => {
  console.log(subjects)
  loading.value = false
})
</script>

<template>
  <h1>Create</h1>

  <h4>Event</h4>
  <hr />
  <div class="text-danger">
    {{ validationErrors }}
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <label class="control-label" for="Ewent_Label">Label</label>
        <input v-model="label" class="form-control" type="text" />
      </div>
      <div class="form-group">
        <label class="control-label" for="Ewent_Description">Description</label>
        <input v-model="description" class="form-control" type="text" />
      </div>
      <div class="form-group">
        <label class="control-label" for="Ewent_From">From</label>
        <input v-model="from" class="form-control" type="datetime-local" />
      </div>
      <div class="form-group">
        <label class="control-label" for="Ewent_Until">Until</label>
        <input v-model="until" class="form-control" type="datetime-local" />
      </div>
      <div class="form-group">
        <label class="control-label" for="Ewent_SubjectId">Subject</label>
        <select v-model="subjectId" class="form-control">
          <option v-for="subject in subjects" :key="subject.id" :value="subject.id">
            {{ subject.label }}
          </option>
        </select>
      </div>
      <div class="form-group">
        <button @click="validateAndCreate()" type="submit" value="Create" class="btn btn-primary">
          Create
        </button>
      </div>
    </div>
  </div>

  <div>
    <RouterLink class="link" :to="{ name: 'Calendar' }">Back to List</RouterLink>
  </div>
</template>

// react_client/src/app/subjects/Create/page.tsx
"use client"

import { IModule } from "@/domain/IModule";
import { ISubject } from "@/domain/ISubject";
import CurriculumService from "@/services/CurriculumService";
import ModuleService from "@/services/ModuleService";
import SubjectService from "@/services/SubjectService";
import { AppContext } from "@/state/AppContext";
import { useContext, useEffect, useState } from "react";

export default function Create() {
    const [isLoading, setIsLoading] = useState(true);
    const [subject, setSubject] = useState<ISubject>();
    const [modules, setModules] = useState<IModule[]>();
    //const { userInfo, setUserInfo } = useContext(AppContext)!;

    const [validationError, setvalidationError] = useState("");

    const [label, setLabel] = useState("a");
    const [description, setDescription] = useState("a");
    const [eap, setEap] = useState(0);
    const [moduleId, setModuleId] = useState("");


    const ValidateAndSave = async () => {

        if (label == ""){
            setvalidationError("Label field is required!");
            return;
        }
        const userInfo = "typeof window !== 'undefined' ? localStorage.getItem('userInfo') : null"
        if (userInfo != undefined){
            const response = await SubjectService.post(userInfo, label, description, eap, moduleId)
            if (response.data) {
                setSubject(response.data);
                window.location.replace("/subjects");
                console.log(response)
            }

            if (response.errors && response.errors.length > 0) {
                setvalidationError(response.errors[0]);
            }
        } else{
            window.location.replace("/Identity/login");
        }
    };

    const loadData = async () => {
        const curricula = await CurriculumService.getAll();
        if (curricula.data){
            const response = await ModuleService.getAll(curricula.data[0].id)
            if (response.data) {
                setModules(response.data);
            }
        }
        setIsLoading(false);
    };
    useEffect(() => { loadData() }, []);

    if (isLoading) return (<h1>Details - LOADING</h1>);

    return (
        <>
        <div className="row">
            <div className="col-md-5">
                <h2>Create Subject</h2>
                <hr />
                <div className="text-danger" role="alert">{validationError}</div>
                <div className="form-floating mb-3">
                    <input
                        value={label}
                        onChange={(e) => { setLabel(e.target.value); setvalidationError(""); }}
                        id="label" type="text" className="form-control" autoComplete="label" placeholder="Label" />
                    <label htmlFor="label" className="form-label">Label</label>
                </div>
                <div className="form-floating mb-3">
                    <input
                        value={description}
                        onChange={(e) => { setDescription(e.target.value); setvalidationError(""); }}
                        id="description" type="text" className="form-control" autoComplete="description" placeholder="Võsa Pets" />
                    <label htmlFor="description" className="form-label">Description</label>
                </div>
                <div className="form-floating mb-3">
                    <input
                        value={eap}
                        onChange={(e) => { setEap(Number.parseInt(e.target.value)); setvalidationError(""); }}
                        id="eap" type="number" className="form-control" autoComplete="eap" placeholder="0" />
                    <label htmlFor="eap" className="form-label">EAP</label>
                </div>

                <div className="form-group">
                    <label className="form-label" htmlFor="moduleId">Module</label>
                    <select
                    value={moduleId}
                    onChange={(e) => { setModuleId(e.target.value) }}
                    className="form-control" id="moduleId">
                        <option></option>
                        {modules!.map((module) => 
                            <option value={module.id} key={module.id}>{module.label}</option>
                        )}
                    </select>
                </div>
                <div>
                    <button onClick={(e) => ValidateAndSave()} className="w-100 btn btn-lg btn-primary">Create</button>
                </div>
            </div>
            <div>
                <a href="./">Back to List</a>
            </div>
        </div>
        </>
    );
}
